apiVersion: v1
kind: PersistentVolume
metadata:
  name: ease-pv
  labels:
    name: ease # name can be anything
spec:
  storageClassName: ease # same storage class as pvc
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.9.2 # NFS server IP address 
    path: "/Public/k8s_storage/ease/"   # NFS share location 
