#
# Redis server
#

apiVersion: v1
kind: Service
metadata:
  name: ease-redis
  labels:
    app: ease
    tier: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: ease
    tier: redis

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ease-redis
  labels:
    app: ease
    tier: redis
spec:
  selector:
    matchLabels:
      app: ease
      tier: redis
  template:
    metadata:
      labels:
        app: ease
        tier: redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379